---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "nc_prod_inventory/prod_hosts.yaml"
        group_file: "nc_prod_inventory/prod_groups.yaml"
        defaults_file: "nc_prod_inventory/prod_defaults.yaml"

runners:
    plugin: threaded
    options:
        num_workers: 10
