---
LEFT:
     hostname: "192.168.11.201"
     port: 830
     groups:
          - "iosxe"
     data:
          region: "iosxe-region"

CENTRE:
     hostname: "192.168.11.202"
     port: 830
     groups:
          - "iosxe"
     data:
          region: "iosxe-region"

RIGHT:
     hostname: "192.168.11.203"
     port: 830
     groups:
          - "iosxe"
     data:
          region: "iosxe-region"
