---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "nc_inventory/nc_hosts.yaml"
        group_file: "nc_inventory/nc_groups.yaml"
        defaults_file: "nc_inventory/nc_defaults.yaml"

runners:
    plugin: threaded
    options:
        num_workers: 10
