native:
  _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-native
  ntp:
    _operation: replace
    server:
      server-list:
        - ip-address: 10.100.100.100
<<<<<<< HEAD
        - ip-address: 10.200.200.200
=======
        - ip-address: 10.250.250.250
>>>>>>> 5ab522b8d98411263613375446a1344124d049c4
        - ip-address: 10.2.2.2
      _xmlns: 'http://cisco.com/ns/yang/Cisco-IOS-XE-ntp'

  router:
    _operation: replace
    router-ospf:
      ospf:
        process-id:
          id: '10'
          network:
            - ip: 0.0.0.0
              wildcard: 255.255.255.255
              area: '0'       
      _xmlns: 'http://cisco.com/ns/yang/Cisco-IOS-XE-ospf'
    ospf:
      id: '10'
      auto-cost:
        reference-bandwidth: '100'
      timers:
        throttle:
          spf:
            delay: '50'
            min-delay: '200'
            max-delay: '5000'
      compatible:
        rfc1583: ''
      _xmlns: 'http://cisco.com/ns/yang/Cisco-IOS-XE-ospf'
