native:
  _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-native
  ntp:
    _operation: replace
    server:
      server-list:
        - ip-address: 10.100.100.100
        - ip-address: 10.200.200.200
      _xmlns: 'http://cisco.com/ns/yang/Cisco-IOS-XE-ntp' 
