native:
  _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-native
  ntp:
    _operation: replace
    server:
      server-list:
        - ip-address: 10.100.100.100
        - ip-address: 10.200.200.200
      _xmlns: 'http://cisco.com/ns/yang/Cisco-IOS-XE-ntp'

  router:
    _operation: replace
    router-ospf:
      ospf:
        process-id:
          id: '10'
          network:
            - ip: 0.0.0.0
              wildcard: 255.255.255.255
              area: '0'
            - ip: 10.0.0.0
              wildcard: 0.255.255.255
              area: '0'           
      _xmlns: 'http://cisco.com/ns/yang/Cisco-IOS-XE-ospf'
    ospf:
      id: '10'
      auto-cost:
        reference-bandwidth: '100'
      timers:
        throttle:
          spf:
            delay: '50'
            min-delay: '200'
            max-delay: '5000'
      compatible:
        rfc1583: ''
      _xmlns: 'http://cisco.com/ns/yang/Cisco-IOS-XE-ospf'
